{{- if (include "jira-software.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jira-software.fullname" . }}
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
type: Opaque
data:
  ATL_JDBC_PASSWORD: {{ .Values.databaseConnection.password | b64enc | quote }}
{{- end }}