apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "confluence-server.fullname" . }}-cm
  labels:
    {{- include "confluence-server.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envVars }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  ATL_JDBC_URL: "jdbc:{{ .Values.databaseConnection.type }}://{{ .Values.databaseConnection.host }}:{{ .Values.databaseConnection.port }}/{{ .Values.databaseConnection.database }}"
  ATL_JDBC_USER: "{{ .Values.databaseConnection.user }}"
  ATL_DB_TYPE: "{{ .Values.databaseConnection.type }}"
  {{- if .Values.ingress.enabled }}
  ATL_PROXY_NAME: {{ (index .Values.ingress.hosts 0).host | quote }}
  ATL_PROXY_PORT: {{ if .Values.ingress.tls }}"443"{{ else }}"80"{{ end }}
  ATL_TOMCAT_SCHEME: {{ if .Values.ingress.tls }}"https"{{ else }}"http"{{ end }}
  ATL_TOMCAT_SECURE: {{ if .Values.ingress.tls }}"true"{{ else }}"false"{{ end }}
  {{- end }}
