{{- if (include "confluence-server.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "confluence-server.fullname" . }}
  labels:
    {{- include "confluence-server.labels" . | nindent 4 }}
type: Opaque
data:
  ATL_JDBC_PASSWORD: {{ .Values.databaseConnection.password | b64enc | quote }}
{{- end }}